wso2/kubernetes-mi

- README.md
- helm/micro-integrator/Chart.yaml
- helm/micro-integrator/README.md
- helm/micro-integrator/confs/logstash/logstash.conf
- helm/micro-integrator/confs/logstash/logstash.yml
- helm/micro-integrator/templates/NOTES.txt
- helm/micro-integrator/templates/_helpers.tpl
- helm/micro-integrator/templates/deployment.yaml
- helm/micro-integrator/templates/ingress.yaml
- helm/micro-integrator/templates/logstash-conf.yaml
- helm/micro-integrator/templates/logstash-elasticsearch-creds.yaml
- helm/micro-integrator/templates/logstash-yml.yaml
- helm/micro-integrator/templates/secrets.yaml
- helm/micro-integrator/templates/service.yaml
- helm/micro-integrator/values.yaml
>  Fixes #1 
>Helm
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
> Add initial content for the repo

- .gitignore
- CONTRIBUTING.md
> This PR adds instruction documentation for contributors.
> Add Instruction Documentation for Contributors
> [1.2.0] Add Instruction Documentation for Contributors

- .gitignore
- CONTRIBUTING.md
- README.md
- helm/micro-integrator/Chart.yaml
- helm/micro-integrator/README.md
- helm/micro-integrator/confs/logstash/logstash.conf
- helm/micro-integrator/confs/logstash/logstash.yml
- helm/micro-integrator/templates/NOTES.txt
- helm/micro-integrator/templates/_helpers.tpl
- helm/micro-integrator/templates/deployment.yaml
- helm/micro-integrator/templates/ingress.yaml
- helm/micro-integrator/templates/logstash-conf.yaml
- helm/micro-integrator/templates/logstash-elasticsearch-creds.yaml
- helm/micro-integrator/templates/logstash-yml.yaml
- helm/micro-integrator/templates/secrets.yaml
- helm/micro-integrator/templates/service.yaml
- helm/micro-integrator/values.yaml
> Merge 1.2.0 branch with master branch - 2020-08-04.
> Merge 1.2.0 branch with master branch
> Merge 1.2.0 branch with master branch - 2020-08-04

- helm/micro-integrator/templates/deployment.yaml
- helm/micro-integrator/templates/ingress.yaml
> This PR exposes the `healthz` endpoint to external traffic. This fixes #5 
> Expose the `healthz` endpoint to external traffic.
> Expose health endpoint

- helm/micro-integrator/README.md
- helm/micro-integrator/templates/deployment.yaml
- helm/micro-integrator/templates/mgt-ingress.yaml
- helm/micro-integrator/templates/service.yaml
- helm/micro-integrator/templates/services-ingress.yaml
- helm/micro-integrator/values.yaml
> This PR exposes the Management endpoint to the external traffic. This fixes #7. 
> Exposes the Management endpoint to the external traffic.
> Expose Management endpoint

- helm/micro-integrator/README.md
- helm/micro-integrator/templates/deployment.yaml
- helm/micro-integrator/values.yaml
> Remove minReadySeconds attribute

- helm/micro-integrator/values.yaml
> This PR fixes #11. 
> Add an example for setting an environment variable.
>  Add a commented example for defining an environment variable.
> [1.2.0] Add an example for setting an environment variable

- CHANGELOG.md
> This PR introduces the changelog. This fixes #14 
> Add the Changelog
> [1.2.0] Add the Changelog

- CHANGELOG.md
- helm/micro-integrator/README.md
- helm/micro-integrator/templates/deployment.yaml
- helm/micro-integrator/templates/ingress.yaml
- helm/micro-integrator/templates/mgt-ingress.yaml
- helm/micro-integrator/templates/service.yaml
- helm/micro-integrator/templates/services-ingress.yaml
- helm/micro-integrator/values.yaml
> [1.2.0] Merge 1.2.0 branch into Master branch - 2020-08-18

- helm/micro-integrator/auth.json
> This PR fixes #17 
> Provide a docker image pull secret to pull docker images from the private registry.
> [1.2.x] Add auth.json file

- CHANGELOG.md
- README.md
- helm/micro-integrator/README.md
> [1.2.x] Update documentation for the next release

- CHANGELOG.md
- README.md
- helm/micro-integrator/README.md
- helm/micro-integrator/auth.json
> This PR merges `1.2.x` branch into `master` branch. This fixes #21.
> [1.2.x] Merge 1.2.x branch into Master branch - 2020-08-26

- helm/micro-integrator/Chart.yaml
> [1.2.x] Update chart version

- helm/micro-integrator/Chart.yaml
>  This PR merge `1.2.x` branch into the `master` branch.  This fixes #22.
> [1.2.x] Merge 1.2.x branch into Master branch -2020-08-26

- CHANGELOG.md
> [1.2.0] Update the changelog

- helm/micro-integrator/templates/_helpers.tpl
- helm/micro-integrator/templates/deployment.yaml
Use updates 2.0 images when subscription enabled.
> Use updates 2.0 images when subscription enabled.

- CHANGELOG.md
- helm/micro-integrator/Chart.yaml
- helm/micro-integrator/README.md
> Prepare for release 1.2.0.4

- CHANGELOG.md
- helm/micro-integrator/Chart.yaml
- helm/micro-integrator/README.md
- helm/micro-integrator/templates/_helpers.tpl
- helm/micro-integrator/templates/deployment.yaml
> Merge 1.2.x into master

- helm/micro-integrator/templates/deployment.yaml
> Fix image pull credentials

- CHANGELOG.md
- helm/micro-integrator/Chart.yaml
- helm/micro-integrator/README.md
> Prepare for release 1.2.0.5

- CHANGELOG.md
> update change log for release 1.2.0.5

- CHANGELOG.md
- helm/micro-integrator/Chart.yaml
- helm/micro-integrator/README.md
- helm/micro-integrator/templates/NOTES.txt
- helm/micro-integrator/templates/wso2mi-management-ingress.yaml
- helm/micro-integrator/templates/wso2mi-services-ingress.yaml
- helm/micro-integrator/values.yaml
> To support MI 4.1.0
> To upgrade ingress API version
> Update Helm artifacts for 4.1.0 release

- CHANGELOG.md
- helm/micro-integrator/Chart.yaml
- helm/micro-integrator/README.md
- helm/micro-integrator/templates/NOTES.txt
- helm/micro-integrator/templates/wso2mi-management-ingress.yaml
- helm/micro-integrator/templates/wso2mi-services-ingress.yaml
- helm/micro-integrator/values.yaml
> Merge 4.1.x to master

- helm/micro-integrator/Chart.yaml
- helm/micro-integrator/README.md
- helm/micro-integrator/templates/NOTES.txt
- helm/micro-integrator/values.yaml
> Add Kubernetes artifacts to support MI 4.2.0
> Add support for MI 4.2.0

- CHANGELOG.md
- helm/micro-integrator/README.md
- helm/micro-integrator/values.yaml
> Change default Docker images to WSO2 private Docker images
> Update README file
> Update CHANGELOG
> Update Helm charts for 4.2.0 release

- CHANGELOG.md
- helm/micro-integrator/Chart.yaml
- helm/micro-integrator/README.md
- helm/micro-integrator/templates/NOTES.txt
- helm/micro-integrator/values.yaml
> Merge 4.2.x to master

- README.md
Add deprecation note and redirect to helm-mi repo
> Add deprecation note and redirect to helm-mi repo
